config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #homeコントローラ
  root "home#user_top"
  get "hairdresser_top" => "home#hairdresser_top", as: "hairdresser_top"
  get "about" => "home#about", as: "about"
  get "deadline" => "home#deadline", as: "deadline"
  
  #users::reservationsコントローラ users::hairdressersコントローラ  namespaceを使う時は使っていないものより上に書く 思い通りのrutingにならないerrorがでた
  namespace :users do
    get "set_week_calendar_reservation" => "reservations#set_week_calendar_reservation", as: "set_week_calendar_reservation"
    get "set_month_calendar_reservation" => "reservations#set_month_calendar_reservation", as: "set_month_calendar_reservation"
    resources :reservations, only: [:edit, :index]
    patch "various_update" => "reservations#various_update", as: "various_update"
    post "pay" => "reservations#pay", as: "card_resevation_pay"
    post "cancel" => "reservations#cancel", as: "reservation_cancel"
    get "complete" => "reservations#complete", as: "complete"
    resources :hairdressers, only: [:show, :index]
  end
  
  #usersコントローラ
  resources :users, only: [:edit, :create, :update]
  post "user/resend" => "users#resend", as: "user_resend"
  patch "user/password" => "users#password_update", as: "user_password_update"
  post "user/login" => "users#login", as: "user_login"
  post "user/logout" => "users#logout", as: "user_logout"
  get "user/activation" => "users#activation", as: "user_activation"
  get "user/sex_choice" => "users#sex_choice", as: "sex_choice"
  post "user/twitter_create" => "users#twitter_create", as: "twitter_create"
  post "user/guide" => "users#guide", as: "user_guide"
  post "user/password_reset" => "users#password_reset", as: "user_password_reset"
  get "user/password_update_as_forget" => "users#password_update_as_forget", as: "user_password_update_as_forget"
  patch "user/password_update_when_not_login" => "users#password_update_when_not_login", as: "user_password_update_when_not_login"

  #twitter認証のコールバック
  get '/auth/:provider/callback' => 'users#twitter' #url入力だとrootにいく
  get "/auth/failure", :to => 'users#twitter_failure' #この書き方にしないとhomesコントローラを探しにいく

  #hairdressers::reservationsコントローラ namespaceを使う時は使っていないものより上に書く 思い通りのrutingにならないerrorがでた
  namespace :hairdressers do
      get "set_week_calendar_reservation" => "reservations#set_week_calendar_reservation", as: "set_week_calendar_reservation"
      post "create_destroy_reservation" => "reservations#create_destroy_reservation", as: "create_destroy_reservation"
      get "set_month_calendar_reservation" => "reservations#set_month_calendar_reservation", as: "set_month_calendar_reservation"
      get "calendar_index" => "reservations#calendar_index", as: "calendar_index"
      post "calendar_show" => "reservations#calendar_show", as: "calendar_show"
      resources :reservations, only: [:new, :index, :create, :destroy]
      get "cancel_index" => "reservations#cancel_index", as: "cancel_index"
  end

  #hairdressersコントローラ
  resources :hairdressers, only: [:show, :edit, :index, :create, :update]
  post "hairdresser/resend" => "hairdressers#resend", as: "hairdresser_resend"
  patch "hairdresser/password" => "hairdressers#password_update", as: "hairdresser_password_update"
  post "hairdresser/login" => "hairdressers#login", as: "hairdresser_login"
  post "hairdresser/logout" => "hairdressers#logout", as: "hairdresser_logout"
  get "hairdresser/wait/:id" => "hairdressers#wait", as: "hairdresser_wait"
  get "hairdresser/activation" => "hairdressers#activation", as: "hairdresser_activation"
  post "hairdresser/guide" => "hairdressers#guide", as: "hairdresser_guide"
  post "hairdresser/password_reset" => "hairdressers#password_reset", as: "hairdresser_password_reset"
  get "hairdresser/password_update_as_forget" => "hairdressers#password_update_as_forget", as: "hairdresser_password_update_as_forget"
  patch "hairdresser/password_update_when_not_login" => "hairdressers#password_update_when_not_login", as: "hairdresser_password_update_when_not_login"

  #adminsコントローラー
  get "admins/user_index" => "admins#user_index", as: "admins_user_index"
  get "admins/hairdresser_index" => "admins#hairdresser_index", as: "admins_hairdresser_index"
  get "admins/user_chart" => "admins#user_chart", as: "admins_user_chart"
  get "admins/hairdresser_chart" => "admins#hairdresser_chart", as: "admins_hairdresser_chart"
  get "admins/sell_chart" => "admins#sell_chart", as: "admins_sell_chart"
  get "admins/login_form" => "admins#login_form", as: "admins_login_form"
  post "admins/login" => "admins#login", as: "admins_login"
  get "admins/hairdresser_judge_index" => "admins#hairdresser_judge_index", as: "admins_hairdresser_judge_index"
  patch "admins/permit/:id" => "admins#permit", as: "admins_permit"
  get "admins/reject/:id" => "admins#reject_form", as: "admins_reject_form"
  patch "admins/reject/:id" => "admins#reject", as: "admins_reject"
  post "admins/logout" => "admins#logout", as: "admins_logout"
  
  #menusコントローラ
  resources :menus, only: [:new, :index, :create, :edit, :update]
  post "menus/status_down" => "menus#status_down", as: "status_down"
  get "menus/preparation" => "menus#preparation", as: "preparation"
  post "menus/status_update" => "menus#status_update", as: "status_update"
  get "menus/choice" => "menus#choice", as: "menu_choice"
  
  #searchコントローラ
  get "search/search_index" => "search#search_index", as: "search_index"
  post "search/top_hairdresser" => "search#top_hairdresser", as: "top_hairdresser"
  post "search_data" => "search#search_data", as: "search_data"
  get "search_data" => "search#search_data"
  post "strong_search" => "search#strong_search", as: "strong_search"
  get "strong_search" => "search#strong_search"
  post "today_hairdresser_and_menu" => "search#today_hairdresser_and_menu", as: "today_hairdresser_and_menu"
  post "tomorrow_hairdresser_and_menu" => "search#tomorrow_hairdresser_and_menu", as: "tomorrow_hairdresser_and_menu"

  #style_imagesコントローラ
  resources :style_images, only: [:edit, :update]
  post "destroy/preparation" => "style_images#destroy_preparation", as: "destroy_preparation"

  #user_cardsコントラーラ
  resources :user_cards, only: [:create, :destroy]
  
  #hairdresser_commentsコントローラ
  resources :hairdresser_comments, only: [:edit, :update, :index]

  #chatsコントローラ
  get "user_chat" => "chats#user_chat", as: "user_chat"
  get "hairdresser_chat" => "chats#hairdresser_chat", as: "hairdresser_chat"
  post "message_create" => "chats#message_create", as: "message_create"
  post "receive_message" => "chats#receive_message", as: "receive_message"
  post "room" => "chats#room", as: "room"
  post "notification" => "chats#notification"
  post "chat_room_search" => "chats#chat_room_search", as: "chat_room_search"

  #favoritesコントローラ
  resources :favorites, only: [:index, :create, :destroy]

  #noticesコントローラ
  post "notice/message" => "notices#notice_message_modal", as: "notice_message_modal" 
  post "notice/reservation" => "notices#notice_reservation_modal", as: "notice_reservation_modal" 
  post "notice/cancel" => "notices#notice_cancel_modal", as: "notice_cancel_modal" 

  mount ActionCable.server => '/cable'
end

app/views/admins/_hairdresser_chart_index.html.erb
<div class="container" style="font-size: 0; padding-top: 10px;">
    <%= link_to admins_user_chart_path do %>
        <div class="admin_data border_none">
            <p class="admin_data_option">会員データ</p>
        </div>
    <% end %>
    <%= link_to admins_hairdresser_chart_path do %>
        <div class="admin_data border">
            <p class="admin_data_option">美容師データ</p>
        </div>
    <% end %>
    <%= link_to admins_sell_chart_path do %>
        <div class="admin_data border_none">
            <p class="admin_data_option">売り上げデータ</p>
        </div>
    <% end %>
</div>
<h1 class="res_font3 res_center">週間美容師数推移</h1>
<div class="chart">
    <canvas id="recent_week_chart"></canvas> <!--canvas要素は、グラフィックなどが描写可能なビットマップキャンバスを提供します。-->
</div>
<%= link_to "前の週", admins_hairdresser_chart_path(pre_week_index: @week_index_standard), remote: true, class: "color" %>
<% if @week_index_standard != Date.today.end_of_week %>
    <%= link_to "次の週", admins_hairdresser_chart_path(next_week_index: @week_index_standard), remote: true, class: "color" %>
<% end %>

<h1 class="res_font3 res_center">月間美容師数推移</h1>
<div class="chart">
    <canvas id="recent_month_chart"></canvas> <!--canvas要素は、グラフィックなどが描写可能なビットマップキャンバスを提供します。-->
</div>
<%= link_to "前の月", admins_hairdresser_chart_path(pre_month_index: @month_index_standard), remote: true, class: "color" %>
<% if @month_index_standard != Date.today.end_of_month %>
    <%= link_to "次の月", admins_hairdresser_chart_path(next_month_index: @month_index_standard), remote: true, class: "color" %>
<% end %>

<h1 class="res_font3 res_center">新規美容師登録者数推移(日別)</h1>
<div class="chart">
    <canvas id="day_chart"></canvas> <!--canvas要素は、グラフィックなどが描写可能なビットマップキャンバスを提供します。-->
</div>
<%= link_to "前の週", admins_hairdresser_chart_path(pre_day: @day_standard), remote: true, class: "color" %>
<% if @day_standard != Date.today %>
    <%= link_to "次の週", admins_hairdresser_chart_path(next_day: @day_standard), remote: true, class: "color" %>
<% end %>

<h1 class="res_font3 res_center">週間新規美容師登録者数推移</h1>
<div class="chart">
    <canvas id="week_chart"></canvas> <!--canvas要素は、グラフィックなどが描写可能なビットマップキャンバスを提供します。-->
</div>
<%= link_to "前の週", admins_hairdresser_chart_path(pre_week: @week_standard), remote: true, class: "color" %>
<% if @week_standard != Date.today.beginning_of_week %>
    <%= link_to "次の週", admins_hairdresser_chart_path(next_week: @week_standard), remote: true, class: "color" %>
<% end %>

<h1 class="res_font3 res_center">月間新規美容師登録者数推移</h1>
<div class="chart">
    <canvas id="month_chart"></canvas> <!--canvas要素は、グラフィックなどが描写可能なビットマップキャンバスを提供します。-->
</div>
<%= link_to "前の月", admins_hairdresser_chart_path(pre_month: @month_standard), remote: true, class: "color" %>
<% if @month_standard != Date.today %>
    <%= link_to "次の月", admins_hairdresser_chart_path(next_month: @month_standard), remote: true, class: "color" %>
<% end %>

<!--jsファイルに書きたかったが、length of nulというエラーがでて嫌だったのでここに書く-->
<script>
    //週間美容師数推移
  　var ctx = document.getElementById("recent_week_chart");
    myLineChart = new Chart(ctx, {
        type: 'line',
        data: {
            labels: <%= @time_week_index_arry_update %>,
            datasets: [
                {
                    label: '人数(人)',
                    data: <%= @hairdresser_week_index_arry_update %>,
                    borderColor: "red",
                    backgroundColor: "rgba(0,0,0,0)",
                    lineTension: 0  //グラフの曲がり具合を表す 0にすると折れ線グラフになる
                },
            ],
        },
        options: {
            title: {
                display: false,
                text: ''
            },
            scales: {
                yAxes: [{  //y軸の設定
                    ticks: {
                        //suggestedMax: 80,    //データがこの値を超えたらその値がmaxに自動でなる
                        suggestedMin: 0,
                        stepSize: <%=@step_number%>,
                        callback: function(value, index, values){
                            return  value +  '人'
                        }
                    }
                }]
            },
        }
    });
    
    //月間美容師数推移
    var ctx = document.getElementById("recent_month_chart");
    myLineChart = new Chart(ctx, {
        type: 'line',
        data: {
            labels: <%= @time_month_index_arry_update %>,
            datasets: [
                {
                    label: '人数(人)',
                    data: <%= @hairdresser_month_index_arry_update %>,
                    borderColor: "red",
                    backgroundColor: "rgba(0,0,0,0)",
                    lineTension: 0  //グラフの曲がり具合を表す 0にすると折れ線グラフになる
                },
            ],
        },
        options: {
            title: {
                display: false,
                text: ''
            },
            scales: {
                yAxes: [{  //y軸の設定
                    ticks: {
                        //suggestedMax: 80,    //データがこの値を超えたらその値がmaxに自動でなる
                        suggestedMin: 0,
                        stepSize: <%=@step_number%>,
                        callback: function(value, index, values){
                            return  value +  '人'
                        }
                    }
                }]
            },
        }
    });

    //美容師登録者数推移(日別)
    var ctx = document.getElementById("day_chart");
    myLineChart = new Chart(ctx, {
        type: 'line',
        data: {
            labels: <%= @time_day_arry_update %>,
            datasets: [
                {
                    label: '人数(人)',
                    data: <%= @hairdresser_day_arry_update %>,
                    borderColor: "red",
                    backgroundColor: "rgba(0,0,0,0)",
                    lineTension: 0  //グラフの曲がり具合を表す 0にすると折れ線グラフになる
                },
            ],
        },
        options: {
            title: {
                display: true,
                text: '人数（<%= (@day_standard-6).month %>月<%= (@day_standard-6).day %>日~<%= @day_standard.month %>月<%= @day_standard.day %>日）'
            },
            scales: {
                yAxes: [{  //y軸の設定
                    ticks: {
                        //suggestedMax: 80,    //データがこの値を超えたらその値がmaxに自動でなる
                        suggestedMin: 0,
                        stepSize: <%=@step_number%>,
                        callback: function(value, index, values){
                            return  value +  '人'
                        }
                    }
                }]
            },
        }
    });



    //週間美容師登録者数推移
    var ctx = document.getElementById("week_chart");
    myLineChart = new Chart(ctx, {
        type: 'line',
        data: {
            labels: <%= @time_week_arry_update %>,
            datasets: [
                {
                    label: '人数(人)',
                    data: <%= @hairdresser_week_arry_update %>,
                    borderColor: "red",
                    backgroundColor: "rgba(0,0,0,0)",
                    lineTension: 0  //グラフの曲がり具合を表す 0にすると折れ線グラフになる
                },
            ],
        },
        options: {
            title: {
                display: false,
                text: ''
            },
            scales: {
                yAxes: [{  //y軸の設定
                    ticks: {
                        //suggestedMax: 80,    //データがこの値を超えたらその値がmaxに自動でなる
                        suggestedMin: 0,
                        stepSize: <%=@step_number%>,
                        callback: function(value, index, values){
                            return  value +  '人'
                        }
                    }
                }]
            },
        }
    });

    //月間美容師登録者数推移
    var ctx = document.getElementById("month_chart");
    myLineChart = new Chart(ctx, {
        type: 'line',
        data: {
            labels: <%= @time_month_arry_update %>,
            datasets: [
                {
                    label: '人数(人)',
                    data: <%= @hairdresser_month_arry_update %>,
                    borderColor: "red",
                    backgroundColor: "rgba(0,0,0,0)",
                    lineTension: 0  //グラフの曲がり具合を表す 0にすると折れ線グラフになる
                },
            ],
        },
        options: {
            title: {
                display: false,
                text: ''
            },
            scales: {
                yAxes: [{  //y軸の設定
                    ticks: {
                        //suggestedMax: 80,    //データがこの値を超えたらその値がmaxに自動でなる
                        suggestedMin: 0,
                        stepSize: <%=@step_number%>,
                        callback: function(value, index, values){
                            return  value +  '人'
                        }
                    }
                }]
            },
        }
    });
</script>

app/views/admins/_sell_chart_index.html.erb
<div class="container" style="font-size: 0; padding-top: 10px;">
    <%= link_to admins_user_chart_path, class: "position" do %>
        <div class="admin_data border_none">
            <p class="admin_data_option">会員データ</p>
        </div>
    <% end %>
    <%= link_to admins_hairdresser_chart_path do %>
        <div class="admin_data border_none">
            <p class="admin_data_option">美容師データ</p>
        </div>
    <% end %>
    <%= link_to admins_sell_chart_path do %>
        <div class="admin_data border">
            <p class="admin_data_option">売り上げデータ</p>
        </div>
    <% end %>
</div>
<h1 class="res_font3 res_center">売り上げ推移(日別)</h1>
<div class="chart">
    <canvas id="sell_day_chart"></canvas> <!--canvas要素は、グラフィックなどが描写可能なビットマップキャンバスを提供します。-->
</div>
<%= link_to "前の週", admins_sell_chart_path(pre_day: @day_standard), remote: true, class: "color" %>
<% if @day_standard != Date.today %>
    <%= link_to "次の週", admins_sell_chart_path(next_day: @day_standard), remote: true, class: "color" %>
<% end %>

<h1 class="res_font3 res_center">週間売り上げ推移</h1>
<div class="chart">
    <canvas id="sell_week_chart"></canvas> <!--canvas要素は、グラフィックなどが描写可能なビットマップキャンバスを提供します。-->
</div>
<%= link_to "前の週", admins_sell_chart_path(pre_week: @week_standard), remote: true, class: "color" %>
<% if @week_standard != Date.today %>
    <%= link_to "次の週", admins_sell_chart_path(next_week: @week_standard), remote: true, class: "color" %>
<% end %>

<h1 class="res_font3 res_center">月間売り上げ推移</h1>
<div class="chart">
    <canvas id="sell_month_chart"></canvas> <!--canvas要素は、グラフィックなどが描写可能なビットマップキャンバスを提供します。-->
</div>
<%= link_to "前の月", admins_sell_chart_path(pre_month: @month_standard), remote: true, class: "color" %>
<% if @month_standard != Date.today %>
    <%= link_to "次の月", admins_sell_chart_path(next_week: @month_standard), remote: true, class: "color" %>
<% end %>

<h1 class="res_font3 res_center">週間総売上推移</h1>
<div class="chart">
    <canvas id="sell_week_index_chart"></canvas> <!--canvas要素は、グラフィックなどが描写可能なビットマップキャンバスを提供します。-->
</div>
<%= link_to "前の週", admins_sell_chart_path(pre_week_index: @week_index_standard), remote: true, class: "color" %>
<% if @week_index_standard != Date.today.end_of_week %>
    <%= link_to "次の週", admins_sell_chart_path(next_week_index: @week_index_standard), remote: true, class: "color" %>
<% end %>

<h1 class="res_font3 res_center">月間総売上推移</h1>
<div class="chart">
    <canvas id="sell_month_index_chart"></canvas> <!--canvas要素は、グラフィックなどが描写可能なビットマップキャンバスを提供します。-->
</div>
<%= link_to "前の月", admins_sell_chart_path(pre_month_index: @month_index_standard), remote: true, class: "color" %>
<% if @month_index_standard != Date.today.end_of_month %>
    <%= link_to "次の月", admins_sell_chart_path(next_month_index: @month_index_standard), remote: true, class: "color" %>
<% end %>

<script>
    var ctx = document.getElementById("sell_day_chart");
    myLineChart = new Chart(ctx, {
        type: 'line',
        data: {
            labels: <%= @time_day_arry_update %>,
            datasets: [
                {
                    label: '売り上げ(円)',
                    data: <%= @money_day_arry_update %>,
                    borderColor: "red",
                    backgroundColor: "rgba(0,0,0,0)",
                    lineTension: 0  //グラフの曲がり具合を表す 0にすると折れ線グラフになる
                },
            ],
        },
        options: {
            title: {
                display: false,
                text: ''
            },
            scales: {
                yAxes: [{  //y軸の設定
                    ticks: {
                        //suggestedMax: 80,    //データがこの値を超えたらその値がmaxに自動でなる
                        suggestedMin: 0,
                        stepSize: 1000,
                        callback: function(value, index, values){
                            return  value +  '円'
                        }
                    }
                }]
            },
        }
    });

    var ctx = document.getElementById("sell_week_chart");
    myLineChart = new Chart(ctx, {
        type: 'line',
        data: {
            labels: <%= @time_week_arry_update %>,
            datasets: [
                {
                    label: '売り上げ(円)',
                    data: <%= @money_week_arry_update %>,
                    borderColor: "red",
                    backgroundColor: "rgba(0,0,0,0)",
                    lineTension: 0  //グラフの曲がり具合を表す 0にすると折れ線グラフになる
                },
            ],
        },
        options: {
            title: {
                display: false,
                text: ''
            },
            scales: {
                yAxes: [{  //y軸の設定
                    ticks: {
                        //suggestedMax: 80,    //データがこの値を超えたらその値がmaxに自動でなる
                        suggestedMin: 0,
                        stepSize: 1000,
                        callback: function(value, index, values){
                            return  value +  '円'
                        }
                    }
                }]
            },
        }
    });

    var ctx = document.getElementById("sell_month_chart");
    myLineChart = new Chart(ctx, {
        type: 'line',
        data: {
            labels: <%=  @time_month_arry_update %>,
            datasets: [
                {
                    label: '売り上げ(円)',
                    data: <%= @money_month_arry_update %>,
                    borderColor: "red",
                    backgroundColor: "rgba(0,0,0,0)",
                    lineTension: 0  //グラフの曲がり具合を表す 0にすると折れ線グラフになる
                },
            ],
        },
        options: {
            title: {
                display: false,
                text: ''
            },
            scales: {
                yAxes: [{  //y軸の設定
                    ticks: {
                        //suggestedMax: 80,    //データがこの値を超えたらその値がmaxに自動でなる
                        suggestedMin: 0,
                        stepSize: 1000,
                        callback: function(value, index, values){
                            return  value +  '円'
                        }
                    }
                }]
            },
        }
    });

    var ctx = document.getElementById("sell_week_index_chart");
    myLineChart = new Chart(ctx, {
        type: 'line',
        data: {
            labels: <%= @time_week_index_arry_update %>,
            datasets: [
                {
                    label: '売り上げ(円)',
                    data: <%= @money_week_index_arry_update %>,
                    borderColor: "red",
                    backgroundColor: "rgba(0,0,0,0)",
                    lineTension: 0  //グラフの曲がり具合を表す 0にすると折れ線グラフになる
                },
            ],
        },
        options: {
            title: {
                display: false,
                text: ''
            },
            scales: {
                yAxes: [{  //y軸の設定
                    ticks: {
                        //suggestedMax: 80,    //データがこの値を超えたらその値がmaxに自動でなる
                        suggestedMin: 0,
                        stepSize: 1000,
                        callback: function(value, index, values){
                            return  value +  '円'
                        }
                    }
                }]
            },
        }
    });

    var ctx = document.getElementById("sell_month_index_chart");
    myLineChart = new Chart(ctx, {
        type: 'line',
        data: {
            labels: <%= @time_month_index_arry_update %>,
            datasets: [
                {
                    label: '売り上げ(円)',
                    data: <%= @money_month_index_arry_update %>,
                    borderColor: "red",
                    backgroundColor: "rgba(0,0,0,0)",
                    lineTension: 0  //グラフの曲がり具合を表す 0にすると折れ線グラフになる
                },
            ],
        },
        options: {
            title: {
                display: false,
                text: ''
            },
            scales: {
                yAxes: [{  //y軸の設定
                    ticks: {
                        //suggestedMax: 80,    //データがこの値を超えたらその値がmaxに自動でなる
                        suggestedMin: 0,
                        stepSize: 1000,
                        callback: function(value, index, values){
                            return  value +  '円'
                        }
                    }
                }]
            },
        }
    });
</script>

app/views/admins/hairdresser_chart.html.erb
<div class="container chart_index">
    <%= render "admins/hairdresser_chart_index" %>
</div>

app/views/admins/hairdresser_chart.js.erb
$(".chart_index").html("<%= j(render "admins/hairdresser_chart_index") %>");

app/views/admins/hairdresser_index.html.erb
<div class="container center" style="padding-top: 50px;">
    <h1 class="admin_title">美容師一覧</h1>
    <table class="table vertical">
        <thead>
            <th class="center">id</th><th class="center">名前</th><th class="center">メールアドレス</th><th class="center">店舗名</th><th class="center">店舗住所</th><th class="center">性別</th><th class="center">評価</th>
        </thead>
        <tbody>
            <% @hairdressers.each do |hairdresser| %>
                <tr>
                    <td>
                        <%= hairdresser.id %>
                    </td>
                    <td>
                        <%= link_to users_hairdresser_path(id: hairdresser.id, admin: "admin"), remote: true do %>
                            <p class="reservation_hairdresser_name cursor"><%= hairdresser.name %></p>
                        <% end %>
                    </td>
                    <td>
                        <% if Rails.env.production? %>
                            ***@gmail.com
                        <% else %>
                            <%= hairdresser.email %>
                        <% end %>
                    </td>
                    <td>
                        <%= hairdresser.shop_name %>
                    </td>
                    <td>
                        <%= hairdresser.address %>
                    </td>
                    <td>
                        <%= hairdresser.sex %>
                    </td>
                    <td>
                        <div id="star-rate-index-average-<%= hairdresser.id %>"></div>
                        <% @comments = hairdresser.hairdresser_comments.where.not(rate: 0.0).count %>
                            <script>
                                $('#star-rate-index-average-<%= hairdresser.id %>').raty({
                                size: 36,
                                starOff:  '<%= asset_path('star-off.png') %>',
                                starOn : '<%= asset_path('star-on.png') %>',
                                starHalf: '<%= asset_path('star-half.png') %>',
                                half: true,
                                readOnly: true,
                                //reputation_pointは評価ポイント(星)の合計　@commentsはコメントの数(評価ポイントをくれた人の人数) この二つで平均を出す　
                                score: <%= hairdresser.reputation_point %>/<%= @comments %>,
                                });
                            </script>
                    </td>
                    <td class="vertical_border">
                        <%= link_to users_hairdresser_path(hairdresser.id), remote: true do %>
                            <p class="btn btn-success">詳細</p>
                        <% end %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>
<div id="hairdresser_show" class="back_dark">
</div>

app/views/admins/hairdresser_judge_index.html.erb
<div class="container center" style="padding-top: 50px;">
    <h1 class="admin_title">承認待ち美容師一覧</h1>
    <table class="table vertical">
        <thead>
            <th class="center">名前</th><th class="center">メールアドレス</th><th class="center">店舗名</th><th class="center">店舗住所</th><th class="center">性別</th>
        </thead>
        <tbody>
            <% @hairdressers.each do |hairdresser| %>
                <tr>
                    <td>
                        <%= link_to users_hairdresser_path(hairdresser.id), remote: true do %>
                            <p class="reservation_hairdresser_name cursor"><%= hairdresser.name %></p>
                        <% end %>
                    </td>
                    <td>
                        <% if Rails.env.production? %>
                            ***@gmail.com
                        <% else %>
                            <%= hairdresser.email %>
                        <% end %>
                    </td>
                    <td>
                        <%= hairdresser.shop_name %>
                    </td>
                    <td>
                        <%= hairdresser.address %>
                    </td>
                    <td>
                        <%= hairdresser.sex %>
                    </td>
                    <td class="vertical_border">
                        <%= link_to users_hairdresser_path(hairdresser.id), remote: true do %>
                            <p class="btn btn-success">詳細</p>
                        <% end %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>
<div id="hairdresser_show" class="back_dark">
</div>

app/views/admins/sell_chart.html.erb
<div class="container chart_index">
    <%= render "admins/sell_chart_index" %>
</div>

app/views/admins/sell_chart.js.erb
$(".chart_index").html("<%= j(render "admins/sell_chart_index") %>");

app/views/admins/user_chart.html.erb
<div class="container chart_index">
    <%= render "admins/user_chart_index" %>
</div>