config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #homeコントローラ
  root "home#user_top"
  get "hairdresser_top" => "home#hairdresser_top", as: "hairdresser_top"
  get "about" => "home#about", as: "about"
  get "deadline" => "home#deadline", as: "deadline"
  
  #users::reservationsコントローラ users::hairdressersコントローラ  namespaceを使う時は使っていないものより上に書く 思い通りのrutingにならないerrorがでた
  namespace :users do
    get "set_week_calendar_reservation" => "reservations#set_week_calendar_reservation", as: "set_week_calendar_reservation"
    get "set_month_calendar_reservation" => "reservations#set_month_calendar_reservation", as: "set_month_calendar_reservation"
    resources :reservations, only: [:edit, :index]
    patch "various_update" => "reservations#various_update", as: "various_update"
    post "pay" => "reservations#pay", as: "card_resevation_pay"
    post "cancel" => "reservations#cancel", as: "reservation_cancel"
    get "complete" => "reservations#complete", as: "complete"
    resources :hairdressers, only: [:show, :index]
  end
  
  #usersコントローラ
  resources :users, only: [:edit, :create, :update]
  post "user/resend" => "users#resend", as: "user_resend"
  patch "user/password" => "users#password_update", as: "user_password_update"
  post "user/login" => "users#login", as: "user_login"
  post "user/logout" => "users#logout", as: "user_logout"
  get "user/activation" => "users#activation", as: "user_activation"
  get "user/sex_choice" => "users#sex_choice", as: "sex_choice"
  post "user/twitter_create" => "users#twitter_create", as: "twitter_create"
  post "user/guide" => "users#guide", as: "user_guide"
  post "user/password_reset" => "users#password_reset", as: "user_password_reset"
  get "user/password_update_as_forget" => "users#password_update_as_forget", as: "user_password_update_as_forget"
  patch "user/password_update_when_not_login" => "users#password_update_when_not_login", as: "user_password_update_when_not_login"

  #twitter認証のコールバック
  get '/auth/:provider/callback' => 'users#twitter' #url入力だとrootにいく
  get "/auth/failure", :to => 'users#twitter_failure' #この書き方にしないとhomesコントローラを探しにいく

  #hairdressers::reservationsコントローラ namespaceを使う時は使っていないものより上に書く 思い通りのrutingにならないerrorがでた
  namespace :hairdressers do
      get "set_week_calendar_reservation" => "reservations#set_week_calendar_reservation", as: "set_week_calendar_reservation"
      post "create_destroy_reservation" => "reservations#create_destroy_reservation", as: "create_destroy_reservation"
      get "set_month_calendar_reservation" => "reservations#set_month_calendar_reservation", as: "set_month_calendar_reservation"
      get "calendar_index" => "reservations#calendar_index", as: "calendar_index"
      post "calendar_show" => "reservations#calendar_show", as: "calendar_show"
      resources :reservations, only: [:new, :index, :create, :destroy]
      get "cancel_index" => "reservations#cancel_index", as: "cancel_index"
  end

  #hairdressersコントローラ
  resources :hairdressers, only: [:show, :edit, :index, :create, :update]
  post "hairdresser/resend" => "hairdressers#resend", as: "hairdresser_resend"
  patch "hairdresser/password" => "hairdressers#password_update", as: "hairdresser_password_update"
  post "hairdresser/login" => "hairdressers#login", as: "hairdresser_login"
  post "hairdresser/logout" => "hairdressers#logout", as: "hairdresser_logout"
  get "hairdresser/wait/:id" => "hairdressers#wait", as: "hairdresser_wait"
  get "hairdresser/activation" => "hairdressers#activation", as: "hairdresser_activation"
  post "hairdresser/guide" => "hairdressers#guide", as: "hairdresser_guide"
  post "hairdresser/password_reset" => "hairdressers#password_reset", as: "hairdresser_password_reset"
  get "hairdresser/password_update_as_forget" => "hairdressers#password_update_as_forget", as: "hairdresser_password_update_as_forget"
  patch "hairdresser/password_update_when_not_login" => "hairdressers#password_update_when_not_login", as: "hairdresser_password_update_when_not_login"

  #adminsコントローラー
  get "admins/user_index" => "admins#user_index", as: "admins_user_index"
  get "admins/hairdresser_index" => "admins#hairdresser_index", as: "admins_hairdresser_index"
  get "admins/user_chart" => "admins#user_chart", as: "admins_user_chart"
  get "admins/hairdresser_chart" => "admins#hairdresser_chart", as: "admins_hairdresser_chart"
  get "admins/sell_chart" => "admins#sell_chart", as: "admins_sell_chart"
  get "admins/login_form" => "admins#login_form", as: "admins_login_form"
  post "admins/login" => "admins#login", as: "admins_login"
  get "admins/hairdresser_judge_index" => "admins#hairdresser_judge_index", as: "admins_hairdresser_judge_index"
  patch "admins/permit/:id" => "admins#permit", as: "admins_permit"
  get "admins/reject/:id" => "admins#reject_form", as: "admins_reject_form"
  patch "admins/reject/:id" => "admins#reject", as: "admins_reject"
  post "admins/logout" => "admins#logout", as: "admins_logout"
  
  #menusコントローラ
  resources :menus, only: [:new, :index, :create, :edit, :update]
  post "menus/status_down" => "menus#status_down", as: "status_down"
  get "menus/preparation" => "menus#preparation", as: "preparation"
  post "menus/status_update" => "menus#status_update", as: "status_update"
  get "menus/choice" => "menus#choice", as: "menu_choice"
  
  #searchコントローラ
  get "search/search_index" => "search#search_index", as: "search_index"
  post "search/top_hairdresser" => "search#top_hairdresser", as: "top_hairdresser"
  post "search_data" => "search#search_data", as: "search_data"
  get "search_data" => "search#search_data"
  post "strong_search" => "search#strong_search", as: "strong_search"
  get "strong_search" => "search#strong_search"
  post "today_hairdresser_and_menu" => "search#today_hairdresser_and_menu", as: "today_hairdresser_and_menu"
  post "tomorrow_hairdresser_and_menu" => "search#tomorrow_hairdresser_and_menu", as: "tomorrow_hairdresser_and_menu"

  #style_imagesコントローラ
  resources :style_images, only: [:edit, :update]
  post "destroy/preparation" => "style_images#destroy_preparation", as: "destroy_preparation"

  #user_cardsコントラーラ
  resources :user_cards, only: [:create, :destroy]
  
  #hairdresser_commentsコントローラ
  resources :hairdresser_comments, only: [:edit, :update, :index]

  #chatsコントローラ
  get "user_chat" => "chats#user_chat", as: "user_chat"
  get "hairdresser_chat" => "chats#hairdresser_chat", as: "hairdresser_chat"
  post "message_create" => "chats#message_create", as: "message_create"
  post "receive_message" => "chats#receive_message", as: "receive_message"
  post "room" => "chats#room", as: "room"
  post "notification" => "chats#notification"
  post "chat_room_search" => "chats#chat_room_search", as: "chat_room_search"

  #favoritesコントローラ
  resources :favorites, only: [:index, :create, :destroy]

  #noticesコントローラ
  post "notice/message" => "notices#notice_message_modal", as: "notice_message_modal" 
  post "notice/reservation" => "notices#notice_reservation_modal", as: "notice_reservation_modal" 
  post "notice/cancel" => "notices#notice_cancel_modal", as: "notice_cancel_modal" 

  mount ActionCable.server => '/cable'
end

app/models/user.rb
class User < ApplicationRecord
    attr_accessor :activation_token #仮想的にカラムをつくる
    before_create :create_column #新しくカラムがデータが保存される前に呼ばれる(saveの前)
    
    def create_new_token #ランダムにトークンを発行
        SecureRandom.urlsafe_base64
    end

    def create_activation_digest(token) #渡された文字列のハッシュ値(暗号)を返す gem 'bcrypt', '~> 3.1.7'が必要
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
        BCrypt::Password.create(token, cost: cost)
    end

    def create_column
        self.activation_token = create_new_token #accessorで作った仮想カラムに値を入れる
        self.activation_digest = create_activation_digest(self.activation_token)
        self.activation_deadline_at = Time.now + 600
    end

    #バリデーション
    #nameカラム
    validates :name,
        length: { in: 2..10, message: "は2文字以上10文字以内で入力してください" },
        uniqueness: { message: "はすでに存在します" }

    #emailカラム
    validates :email,
        format: { with: /\A\S+@\S+\.\S+\z/, message: "と認識されませんでした" },
        uniqueness: { message: "はすでに存在します" }

    #passoword_digestカラム
    has_secure_password #パスワードを暗号化して保存するにはこの記述が必要 presenceとpasswordとpassword_confirmationの一致のバリデーションも兼ねている
    validates :password, length: { in: 6..20, message: "は6文字以上20文字以内で入力してください" }, on: :create #これをしないとpasswordを更新しないupdateのときも求められる 

    #sexカラム
    validates :sex, presence: { message: "を選択してください" }

    #モデルの関連付け
    has_many :reservations
    has_many :hairdresser_comments
    has_many :cancel_reservations
    has_many :chats
    has_many :favorites

end


#gem 'bcrypt'とhas_secure_passwordにより次の機能が使える
# セキュアにハッシュ化したパスワードを、データベース内のpassword_digestという属性に保存できるようになる。
# 2つのペアの仮想的な属性（passwordとpassword_confirmation）が使えるようになる。また、存在性と値が一致するかどうかのバリデーションも追加される 。
# authenticateメソッドが使えるようになる（引数の文字列がパスワードと一致するとUserオブジェクトを、間違っているとfalseを返すメソッド）。

app/controllers/users/hairdressers_controller.rb
class Users::HairdressersController < ApplicationController
    def show
        @hairdresser = Hairdresser.find(params[:id])
        @status = @hairdresser.judge_status
        @hairdresser_comments = HairdresserComment.where(hairdresser_id: params[:id]).order(start_time: "DESC") & HairdresserComment.where.not(rate: 0.0).order(start_time: "ASC")

        @menus = @hairdresser.menus.where(status: true)
        @menus_category = @menus.map {|a| a.category}
        @menus_category.uniq!
        @cut = @menus_category.map {|a| a.slice(0,1)} #カット
        @color = @menus_category.map {|a| a.slice(1,1)} #カラー
        @perm = @menus_category.map {|a| a.slice(2,1)} #パーマ
        @curly = @menus_category.map {|a| a.slice(3,1)} #縮毛
        
        #最短予約可能日時を見つける
        @reservations = @hairdresser.reservations.where(status: false).order(start_time: "ASC")
        @arry = @reservations.map {|reservation| reservation.menu.status == true && Time.now <= reservation.start_time}
        @first_number = @arry.index(true)

        @style_image = StyleImage.find_by(hairdresser_id: @hairdresser.id) #ヘアカタログ
    
        if params[:profile].present?
            @profile = true
        end 
        if params[:menu].present?
            @menu = true
        end
        if params[:photo].present?
            @photo = true
        end
        if params[:review].present?
            @review = true
        end
    end
end

app/helpers/users/hairdressers_helper.rb
module Users::HairdressersHelper
end

app/helpers/users/reservations_helper.rb
module Users::ReservationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/templete/_credit.html.erb
<h3>クレジットカード情報入力</h3>
<p>ご利用可能なカードは以下の通りです</p>
<img src="<%= asset_path "visa.gif" %>" class="card_logo">
<img src="<%= asset_path "master.gif" %>" class="card_logo">
<img src="<%= asset_path "jcb.gif" %>" class="card_logo">
<img src="<%= asset_path "amex.gif" %>" class="card_logo">
<img src="<%= asset_path "diner.gif" %>" class="card_logo">
<img src="<%= asset_path "discover.gif" %>" class="card_logo">
<!--
<div class="container center card_register">
    <%= form_with(url: user_cards_path, method: :post, id: "charge-form") do |f|  %>
        <%= f.label "カード番号" %><span class="must">必須</span>
        <%= f.text_field "card_number", class: "number form-control ca_form", value: 4242424242424242  ,maxlength: "16", type: "text", id: "card_number"%>
        <br>
        <%= f.label "有効期限", class: "limit" %><span class="must">必須</span>
        <%= f.select 'exp_month', options_for_select({"--": "", "01": 1, "02": 2, "03": 3, "04": 4, "05": 5, "06": 6, "07": 7, "08": 8, "09": 9, "10": 10, "11": 11, "12": 12}, "")%>
        <span>月/</span>
        <%= f.select 'exp_year', options_for_select({"--": "", "19": 2019, "20": 2020, "21": 2021, "22": 2022, "23": 2023, "24": 2024, "25": 2025, "26": 2026, "27": 2027, "28": 2028, "29": 2029}, "")%>
        <span>年</span>
        <br>
        <%= f.label "セキュリティコード", class: "security"%><span class="must">必須</span>
        <%= f.text_field "cvc", class: "cvc form-control ca_form", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc" %>
        <div>
            <%= f.submit "登録する", id: "token_submit", class: "btn btn-success" %>
        </div>
    <%end%>
</div>
-->
<div id="fda" style="margin-top:100px">
    <div id="v2-demo" class="payjs-outer"><!-- ここにフォームが生成されます --></div>
    <button onclick="onSubmit(event)">登録する</button>
    <span id="token"></span>
</div>
<%= form_with(url: user_cards_path, method: :post, id: "charge-form", local: true) do |f|  %>
<%end%>
<script>
// 公開鍵を登録し、起点となるオブジェクトを取得します
var payjp = Payjp(gon.key)

// elementsを取得します。ページ内に複数フォーム用意する場合は複数取得ください
var elements = payjp.elements()

// element(入力フォームの単位)を生成します
var cardElement = elements.create('card')

// elementをDOM上に配置します
cardElement.mount('#v2-demo')

// ボタンが押されたらtokenを生成する関数を用意します
function onSubmit(event) {
  payjp.createToken(cardElement).then(function(r) {
    // document.querySelector('#token').innerText = r.error ? r.error.message : r.id
    document.getElementById('charge-form').insertAdjacentHTML('beforeend', `<input type="hidden" name="payjp-token" value="${r.id}">`)
    document.getElementById('charge-form').insertAdjacentHTML('beforeend', `<input type="submit" name="commit" value="" id="token_submit" class="btn btn-success display_none" data-disable-with="" type="hidden">`)
    document.getElementById("token_submit").click()
  })
}


</script>

app/views/users/templete/_credit_show.html.erb
<h3>クレジットカード情報</h3>
<div class="containe center">
    <div class="number_hidden">
        <h2>**** **** ****<%=@card_information.last4%></h2>
    </div>
    <% exp_month = @card_information.exp_month.to_s %>  <!--to_sにしないと7行目で文字列と合体できない-->
    <% exp_year = @card_information.exp_year.to_s.slice(2,3) %>
    <span class="time_limit">有効期限</span><%= exp_month + " / " + exp_year %>
    <div class="card_delete">
        <%= link_to "削除", user_card_path(@current_user.id), method: :delete, data: {confirm: "本当に削除しますか?"}, class: "btn btn-danger"%>
    </div>
</div>

app/views/users/templete/_password.html.erb
<% if @current_user.email.include?("twitter") == false %>
    <div class="center">
        <p style="margin-bottom: 30px;">現在のパスワードを入力してください</p>
        <p class="show_password_error error"></p>
        <%= form_with(url: edit_user_path(@current_user.id), method: :get) do |f| %>
            <p class="user_register_form_password_error error"></p>
            <%= f.password_field :current_password, class: "user_show_form password name user_register_form_element" %>
            <div>
                <%= f.submit "完了", class: "btn btn-success", style: "width: 150px; margin-top: 60px" %>
            </div>
        <% end %>
    </div>
<% else %>
    <p>twitterアカウントのため、操作できません</p>
<% end %>

app/views/users/templete/_profile.html.erb
<div style="margin-bottom: 30px;">
    <% if @current_user.sex == "男性" %>
        <img src="<%= asset_path "male2.png" %>">
    <% elsif @current_user.sex == "女性" %>
        <img src="<%= asset_path "female2.png" %>">
    <% end %>
</div>
<%= form_with(model: @current_user) do |f| %>
    <p>ユーザー名</p>
    <p class="user_register_form_name_error error"></p>
    <%= f.text_field :name, class: "user_show_form name user_register_form_element" %>
    <% if @current_user.email.include?("twitter") %>
        <p style="color: blue; margin-bottom: 30px;">twitterアカウントでログインしています</p>
    <% else %>
        <p>メールアドレス</p>
        <p class="user_show_form user_show_email"><%=@current_user.email%></p>
    <% end %>
    <div>
        <span class="man cursor2" id="man">
            <span>男性</span>
            <%= f.radio_button :sex, :男性, id: "sex_man"%>
        </span>
        <span class="woman cursor2" id="woman">
            <span>女性</span>
            <%= f.radio_button :sex, :女性, id: "sex_woman"%>
        <span>
    </div>
    <div>
        <%= f.submit "更新", class: "btn btn-success", style: "width: 150px; margin-top: 60px" %>
    </div>
<% end %>

app/views/users/templete/_reset_password.html.erb
<div class="center">
    <h3>パスワードの更新</h3>
    <%= form_with(model: @current_user, url: user_password_update_path, method: :patch) do |f| %>
        <p>パスワード</p>
        <p class="user_register_form_password_error error"></p>
        <%= f.password_field :password, class: "user_show_form password name user_register_form_element" %>
        <p>パスワード確認</p>
        <%= f.password_field :password_confirmation, class: "user_show_form password name user_register_form_element" %>
        <div>
            <%= f.submit "完了", class: "btn btn-success", style: "width: 150px; margin-top: 60px" %>
        </div>
    <% end %>
</div>