config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #homeコントローラ
  root "home#user_top"
  get "hairdresser_top" => "home#hairdresser_top", as: "hairdresser_top"
  get "about" => "home#about", as: "about"
  get "deadline" => "home#deadline", as: "deadline"
  
  #users::reservationsコントローラ users::hairdressersコントローラ  namespaceを使う時は使っていないものより上に書く 思い通りのrutingにならないerrorがでた
  namespace :users do
    get "set_week_calendar_reservation" => "reservations#set_week_calendar_reservation", as: "set_week_calendar_reservation"
    get "set_month_calendar_reservation" => "reservations#set_month_calendar_reservation", as: "set_month_calendar_reservation"
    resources :reservations, only: [:edit, :index]
    patch "various_update" => "reservations#various_update", as: "various_update"
    post "pay" => "reservations#pay", as: "card_resevation_pay"
    post "cancel" => "reservations#cancel", as: "reservation_cancel"
    get "complete" => "reservations#complete", as: "complete"
    resources :hairdressers, only: [:show, :index]
  end
  
  #usersコントローラ
  resources :users, only: [:edit, :create, :update]
  post "user/resend" => "users#resend", as: "user_resend"
  patch "user/password" => "users#password_update", as: "user_password_update"
  post "user/login" => "users#login", as: "user_login"
  post "user/logout" => "users#logout", as: "user_logout"
  get "user/activation" => "users#activation", as: "user_activation"
  get "user/sex_choice" => "users#sex_choice", as: "sex_choice"
  post "user/twitter_create" => "users#twitter_create", as: "twitter_create"
  post "user/guide" => "users#guide", as: "user_guide"
  post "user/password_reset" => "users#password_reset", as: "user_password_reset"
  get "user/password_update_as_forget" => "users#password_update_as_forget", as: "user_password_update_as_forget"
  patch "user/password_update_when_not_login" => "users#password_update_when_not_login", as: "user_password_update_when_not_login"

  #twitter認証のコールバック
  get '/auth/:provider/callback' => 'users#twitter' #url入力だとrootにいく
  get "/auth/failure", :to => 'users#twitter_failure' #この書き方にしないとhomesコントローラを探しにいく

  #hairdressers::reservationsコントローラ namespaceを使う時は使っていないものより上に書く 思い通りのrutingにならないerrorがでた
  namespace :hairdressers do
      get "set_week_calendar_reservation" => "reservations#set_week_calendar_reservation", as: "set_week_calendar_reservation"
      post "create_destroy_reservation" => "reservations#create_destroy_reservation", as: "create_destroy_reservation"
      get "set_month_calendar_reservation" => "reservations#set_month_calendar_reservation", as: "set_month_calendar_reservation"
      get "calendar_index" => "reservations#calendar_index", as: "calendar_index"
      post "calendar_show" => "reservations#calendar_show", as: "calendar_show"
      resources :reservations, only: [:new, :index, :create, :destroy]
      get "cancel_index" => "reservations#cancel_index", as: "cancel_index"
  end

  #hairdressersコントローラ
  resources :hairdressers, only: [:show, :edit, :index, :create, :update]
  post "hairdresser/resend" => "hairdressers#resend", as: "hairdresser_resend"
  patch "hairdresser/password" => "hairdressers#password_update", as: "hairdresser_password_update"
  post "hairdresser/login" => "hairdressers#login", as: "hairdresser_login"
  post "hairdresser/logout" => "hairdressers#logout", as: "hairdresser_logout"
  get "hairdresser/wait/:id" => "hairdressers#wait", as: "hairdresser_wait"
  get "hairdresser/activation" => "hairdressers#activation", as: "hairdresser_activation"
  post "hairdresser/guide" => "hairdressers#guide", as: "hairdresser_guide"
  post "hairdresser/password_reset" => "hairdressers#password_reset", as: "hairdresser_password_reset"
  get "hairdresser/password_update_as_forget" => "hairdressers#password_update_as_forget", as: "hairdresser_password_update_as_forget"
  patch "hairdresser/password_update_when_not_login" => "hairdressers#password_update_when_not_login", as: "hairdresser_password_update_when_not_login"

  #adminsコントローラー
  get "admins/user_index" => "admins#user_index", as: "admins_user_index"
  get "admins/hairdresser_index" => "admins#hairdresser_index", as: "admins_hairdresser_index"
  get "admins/user_chart" => "admins#user_chart", as: "admins_user_chart"
  get "admins/hairdresser_chart" => "admins#hairdresser_chart", as: "admins_hairdresser_chart"
  get "admins/sell_chart" => "admins#sell_chart", as: "admins_sell_chart"
  get "admins/login_form" => "admins#login_form", as: "admins_login_form"
  post "admins/login" => "admins#login", as: "admins_login"
  get "admins/hairdresser_judge_index" => "admins#hairdresser_judge_index", as: "admins_hairdresser_judge_index"
  patch "admins/permit/:id" => "admins#permit", as: "admins_permit"
  get "admins/reject/:id" => "admins#reject_form", as: "admins_reject_form"
  patch "admins/reject/:id" => "admins#reject", as: "admins_reject"
  post "admins/logout" => "admins#logout", as: "admins_logout"
  
  #menusコントローラ
  resources :menus, only: [:new, :index, :create, :edit, :update]
  post "menus/status_down" => "menus#status_down", as: "status_down"
  get "menus/preparation" => "menus#preparation", as: "preparation"
  post "menus/status_update" => "menus#status_update", as: "status_update"
  get "menus/choice" => "menus#choice", as: "menu_choice"
  
  #searchコントローラ
  get "search/search_index" => "search#search_index", as: "search_index"
  post "search/top_hairdresser" => "search#top_hairdresser", as: "top_hairdresser"
  post "search_data" => "search#search_data", as: "search_data"
  get "search_data" => "search#search_data"
  post "strong_search" => "search#strong_search", as: "strong_search"
  get "strong_search" => "search#strong_search"
  post "today_hairdresser_and_menu" => "search#today_hairdresser_and_menu", as: "today_hairdresser_and_menu"
  post "tomorrow_hairdresser_and_menu" => "search#tomorrow_hairdresser_and_menu", as: "tomorrow_hairdresser_and_menu"

  #style_imagesコントローラ
  resources :style_images, only: [:edit, :update]
  post "destroy/preparation" => "style_images#destroy_preparation", as: "destroy_preparation"

  #user_cardsコントラーラ
  resources :user_cards, only: [:create, :destroy]
  
  #hairdresser_commentsコントローラ
  resources :hairdresser_comments, only: [:edit, :update, :index]

  #chatsコントローラ
  get "user_chat" => "chats#user_chat", as: "user_chat"
  get "hairdresser_chat" => "chats#hairdresser_chat", as: "hairdresser_chat"
  post "message_create" => "chats#message_create", as: "message_create"
  post "receive_message" => "chats#receive_message", as: "receive_message"
  post "room" => "chats#room", as: "room"
  post "notification" => "chats#notification"
  post "chat_room_search" => "chats#chat_room_search", as: "chat_room_search"

  #favoritesコントローラ
  resources :favorites, only: [:index, :create, :destroy]

  #noticesコントローラ
  post "notice/message" => "notices#notice_message_modal", as: "notice_message_modal" 
  post "notice/reservation" => "notices#notice_reservation_modal", as: "notice_reservation_modal" 
  post "notice/cancel" => "notices#notice_cancel_modal", as: "notice_cancel_modal" 

  mount ActionCable.server => '/cable'
end

app/controllers/admins/hairdressers_controller.rb
class Admins::HairdressersController < ApplicationController

    def hairdresser_judge_index
        @hairdressers = Hairdresser.where(status: 0)
    end

    def show
        @hairdresser = Hairdresser.find(params[:id])
    end

    def permit
        @hairdresser = Hairdresser.find(params[:id])
        @hairdresser.status = 1
        @hairdresser.save
        redirect_to admins_hairdresser_judge_index_path
    end

end

app/controllers/hairdressers/reservations_controller.rb
class Hairdressers::ReservationsController < ApplicationController

    def index #実際に予約が入っている予約一覧
        @reservations = @current_hairdresser.reservations.where.not(user_id: nil).order(start_time: :asc) #入っている予約を取り出す
        @date_arry = @reservations.all.pluck(:start_time).map {|a| a.to_date}
        @date_arry.uniq!
        @date_number = @date_arry.length

        @notice_reservations = @current_hairdresser.reservations.where.not(notification_status: true)   #まだ通知を受け取っていない予約 この入れ物はupdateするためにつかう
        if @notice_reservations.present?
            flash[:notice_reservations] = @notice_reservations
            @notice_reservations.update_all(:notification_status => true)
        end
    end

    def cancel_index #キャンセルされた予約一覧
        @cancel_reservations = CancelReservation.where(hairdresser_id: @current_hairdresser.id).order(start_time: :asc)
        @date_arry = @cancel_reservations.all.pluck(:start_time).map {|a| a.to_date}
        @date_arry.uniq!
        @date_number = @date_arry.length

        @notice_cancel_reservations = CancelReservation.where(hairdresser_id: @current_hairdresser.id, notification_status: false)
        if @notice_cancel_reservations.present?
            flash.now[:notice_cancel_reservations] = @notice_cancel_reservations
            @notice_cancel_reservations.update_all(:notification_status => true )
        end
    end

    def set_week_calendar_reservation #週間カレンダー
        calendar
        @menu = Menu.find(params[:menu_id])
        @thead_for_hairdresser = true
    end

    def calendar_index
        calendar
        @calendar_for_index = true
    end

    def calendar_show
        @reservations = Reservation.where(start_time: params[:time]).select {|reservation| reservation.menu.hairdresser == @current_hairdresser && reservation.menu.status == true}
        @menus = @reservations.map {|reservation| reservation.menu}
        @time = params[:time]
    end

    def create_destroy_reservation #週間カレンダーからの予約作成 予約の削除も行う
        if params[:start_time].present?
            @reservation_start_time_arry = params[:start_time]
            @reservation_start_time_arry.map! {|a| Reservation.new(start_time: a, menu_id: params[:menu_id], reservation_token: SecureRandom.urlsafe_base64)} #has_secure_tokenが発動しなかった
            Reservation.import @reservation_start_time_arry #これでinsertが一括でできる
        end

        @reservations_user_exist = @current_hairdresser.reservations.where.not(user_id: nil)
        @reservations_user_exist.all.each do |reservation|
            @time_min = reservation.start_time
            @time_max = reservation.start_time + reservation.menu.time*60 -1
            @reservations = @current_hairdresser.reservations.where(start_time: @time_min..@time_max)
            @reservations.update_all(:status => true )
        end

        if params[:start_time_remove].present?
            @reservation_start_time_remove_arry = params[:start_time_remove]
            @reservation_start_time_remove_arry.map! {|a| Reservation.find_by(start_time: a, menu_id: params[:menu_id], user_id: nil)}
            @reservation_id_arry = @reservation_start_time_remove_arry.pluck(:id)
            Reservation.where(id: @reservation_id_arry).destroy_all
        end

        flash[:notice] = "変更を保存しました"
        redirect_to hairdressers_set_week_calendar_reservation_path(menu_id: params[:menu_id], standard_day: params[:standard_day], win_height: params[:win_height])
    end

    def set_month_calendar_reservation
        @reservations = Reservation.where(menu_id: params[:menu_id])
        @menu = Menu.find_by(id: params[:menu_id], hairdresser_id: @current_hairdresser.id)
        if @menu.blank? #フロントで引数を変えられたとき
            flash[:notice_red] = "その操作は禁じられています"
            redirect_to root_path
        end
        if params[:win_height].present? #リンクの 前の月 次の月 をクリックしたらある
            gon.win_height = params[:win_height].to_i
        end
        if params[:start_date].present? #リンクの 前の月 次の月 をクリックしたらある
            @start_year = params[:start_date].to_time.year
            @start_month = params[:start_date].to_time.month
        else
            @start_year = Date.today.year
            @start_month = Date.today.month
        end
        if params[:win_scroll].present? #リンクの カレンダーに戻る をクリックしたらある
            gon.scroll = true
        end
    end

    def new
        @reservation = Reservation.new

        #フォームの初期値
        @year = params[:year].to_i
        @month = params[:month].to_i
        @day = params[:day].to_i
        @hour = params[:hour].to_i
        @min = params[:min].to_i

        @menu = Menu.find_by(id: params[:menu_id], hairdresser_id: @current_hairdresser.id)
        if @menu.present?
            @min_time = Date.new(@year, @month, @day).to_time
            @max_time = Date.new(@year, @month, @day).to_time.end_of_day
            @reservations = @menu.reservations.where(start_time: @min_time..@max_time).order(start_time: :asc) #start_timeカラムが早い日付の順番にで@reservationsを整理する 本当はwhereでどうにかしたかったが、解決策がなくこのような形になった
        else
            flash[:notice_red] = "その操作は禁じられています"
            redirect_to root_path
        end
    end

    def create #月間カレンダーからの予約作成
        @reservation = Reservation.new(reservation_params)
        @menu = Menu.find_by(id: params[:menu_id], hairdresser_id: @current_hairdresser.id)
        if @menu.blank? #フロントで引数を変えられたとき
            flash[:notice_red] = "その操作は禁じられています" #フロントで引数を変更
            redirect_to root_path
        end
        @reservation.menu_id = @menu.id
        @year = @reservation.start_time.year
        @month = @reservation.start_time.month
        @day = @reservation.start_time.day
        @hour = @reservation.start_time.hour
        @min = @reservation.start_time.min
        if @reservation.save
            #newのフォームの初期値を設定
            if @hour == 23 && @min == 30
            else
                @min += 30    #時間を登録したらフォームにはその時間の30分後の時間が初期値として入力されているようにする
            end
            flash[:notice] = "予約を追加しました"
            redirect_to new_hairdressers_reservation_path(menu_id: @reservation.menu_id, year: @year, month: @month, day: @day, hour: @hour, min: @min)
        else
            @min_time = Date.new(@year, @month, @day).to_time
            @max_time = Date.new(@year, @month, @day).to_time.end_of_day
            @reservations = @menu.reservations.where(start_time: @min_time..@max_time).order(start_time: :asc)
            if @reservation.errors.messages[:time_validation_30].present?
                @error = "予約は今日の日時から90日以内の時刻しか予約できません"
            else
                @error = "その時間はすでに登録されています"
            end
            render "hairdressers/reservations/new"
        end
    end

    def destroy
        @reservation = Reservation.find(params[:id])
        if @reservation.menu.hairdresser == @current_hairdresser && @reservation.user_id == nil
            @reservation.destroy
            flash[:notice_red] = "予約を削除しました"
            redirect_to new_hairdressers_reservation_path(year: @reservation.start_time.year, month: @reservation.start_time.month, day: @reservation.start_time.day, hour: @reservation.start_time.hour, min: @reservation.start_time.min, menu_id: @reservation.menu_id )
        else
            flash[:notice_red] = "その操作は禁じられています" #フロントで引数を変更
            redirect_to root_path
        end
    end

    def calendar #インスタンスメソッド
        #カレンダーの週を変える
        if params[:option] == "last"
            @standard_day = Date.new(params[:day][0,4].to_i, params[:day][5,2].to_i, params[:day][8,2].to_i)
            @standard_day -= 7
        elsif params[:option] == "next"
            @standard_day = Date.new(params[:day][0,4].to_i, params[:day][5,2].to_i, params[:day][8,2].to_i)
            @standard_day += 7
        elsif params[:standard_day].present?
            @standard_day = Date.new(params[:standard_day][0,4].to_i, params[:standard_day][5,2].to_i, params[:standard_day][8,2].to_i)
        else
            @standard_day = Date.today
        end

        if params[:win_height].present?
            gon.win_height = params[:win_height].to_i
        end

        #テーブルの真ん中上の年月のviewを整えるのに使う
        @diff = (@standard_day.end_of_month - @standard_day).to_i

        @clock_arry = ["06:00", "06:30", "07:00", "07:30", "08:00", "08:30", "09:00", "09:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00","15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00", "20:30", "21:00", "21:30", "22:00", "22:30", "23:00", "23:30"]

        #配列を作成
        for i in 1..14 do
            if i == 1
                @key_time = Time.local(@standard_day.year, @standard_day.month, @standard_day.day) + 3600*6   #秒で計算している 3600は一時間
                @time_arry = @key_time.to_i.step( (Time.local(@standard_day.year, @standard_day.month, @standard_day.day)+3600*23.5).to_i, 60*30).to_a
                @time_arry.map! {|a| Time.at(a)}
            else
                @key_time = Time.local(@standard_day.year, @standard_day.month, @standard_day.day) + 3600*6 + 3600*24*(i-1)
                @time_next_arry = @key_time.to_i.step( (Time.local(@standard_day.year, @standard_day.month, @standard_day.day)+3600*24*(i-1)+3600*23.5).to_i, 60*30).to_a
                @time_next_arry.map! {|a| Time.at(a)}
                @time_arry.push(@time_next_arry)
            end
        end
        @time_arry.flatten! #この時点では要素はTimeクラス
        @date_arry = @time_arry.map {|a| a.to_date} #これで要素はDateクラス
        @date_arry.uniq!
    end

    private
    def reservation_params
        params.permit(:start_time)
    end
end

app/helpers/admins/hairdressers_helper.rb
module Admins::HairdressersHelper
end

app/helpers/hairdressers_helper.rb
module HairdressersHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/users/hairdressers_helper.rb
module Users::HairdressersHelper
end

app/helpers/users/reservations_helper.rb
module Users::ReservationsHelper
end

app/views/hairdressers/reservations/calendar_index.html.erb
<div class="container">

    <h3 class="center">予定表</h3>
    <P class="center">(このページからは編集できません)</p>

    <!--記号の説明-->
    <div class="explain_simbol res_margin6">
        <span style="color: red;" class="simbol">◎</span>予約可能
        <span style="color: blue;" class="simbol">◎</span>予約あり
        <span class="glyphicon glyphicon-remove simbol" aria-hidden="true"></span>予約不可
    </div>

    <!--ここから週間カレンダー-->
    <table class="week_reservation_table">
        <thead class="table_header" id="table_head">
            <%= render "home/thead", reservation: false %>
        </thead>
        <tbody id="table_body">
            <tr>
                <!--左の時刻表-->
                <th class="border_right table_time">
                    <table>
                        <tbody class="times">
                            <% @clock_arry.each do |clock| %>
                                <tr>
                                    <th class="width4"><%= clock %></th>
                                </tr>
                            <% end %>
                        </tbody>
                    </table>
                </th>
                
                <!--バツマル-->
                <% for i in 0..(@date_arry.length - 1) do %>
                    <th class="border_right table_maru_batu">
                        <!--このテーブルは縦一列-->
                        <table>
                            <tbody class="simbols">
                                <% @time_arry.each do |time| %>
                                    <% if @date_arry[i] == time.to_date %>
                                        <tr>
                                            <td href="<%=time%>" id="<%=time.year%><%=time.month%><%=time.day%><%=time.hour%><%=time.min%>" , class="border_bottom function width3 td_color">
                                                <% if Reservation.where(start_time: time).select {|reservation| reservation.menu.hairdresser == @current_hairdresser && reservation.menu.status == true && reservation.user_id != nil}.present? %>
                                                    <%= link_to hairdressers_calendar_show_path(time: time), method: :post, remote: true do %>
                                                        <p style='color: blue;' class="simbol_exist_reservation">◎</p>
                                                    <% end %>
                                                <% elsif Reservation.where(start_time: time).select {|reservation| reservation.menu.hairdresser == @current_hairdresser && reservation.menu.status == true && reservation.user_id == nil}.present? %>
                                                    <%= link_to hairdressers_calendar_show_path(time: time), method: :post, remote: true do %>
                                                        <p style='color: red;' class="simbol_round">◎</p>
                                                    <% end %>
                                                <% else %>
                                                   <p class="glyphicon glyphicon-remove simbol_remove" aria-hidden="true"></p>
                                                <% end %>
                                            </td>
                                        </tr>
                                    <% end %>
                                <% end %>
                            </tbody>
                        </table>
                    </th>
                <% end %>
                    
                <!--右の時刻表-->
                <th class="table_time">
                    <table>
                        <tbody class="times">
                            <% @clock_arry.each do |clock| %>
                                <tr>
                                    <th class="width4"><%= clock %></th>
                                </tr>
                            <% end %>
                        </tbody>
                    </table>
                </th>

            </tr>
        </tbody>
    </table>

</div>

<div class="back_dark">
</div>

app/views/hairdressers/reservations/calendar_show.js.erb
html = `    
            <div class="calendar_menu_index">
                <span class="glyphicon glyphicon-remove cursor" style="float: right;"></span>
                <p style="font-size: 20px;"><%=@time.to_time.month%>月<%=@time.to_time.day%>日(<%= %w(日 月 火 水 木 金 土)[(@time.to_time).wday] %>)<%=@time.to_time.hour%>時<%=@time.to_time.min%>分のメニュー</p>
                <% @menus.reverse_each do |menu| %>
                    <div class="menu_card_small">
                        <div class="menu_top" >
                            <p class="menu_title"><%= menu.name %></p>
                            <p class="menu_time_small font"><%= menu.time %>分</p>
                            <p class="card_categories_small">
                                <% if menu.category[0,1] == "1" %>
                                    <span class="cut_category category font" style="font-size: 13px;">カット</span>
                                <% end %>
                                <% if menu.category[1,1] == "1" %>
                                    <span class="color_category category font" style="font-size: 13px;">カラー</span>
                                <% end %>
                                <% if menu.category[2,1] == "1" %>
                                    <span class="curly_category category font" style="font-size: 13px;">縮毛矯正</span>
                                <% end %>
                                <% if menu.category[3,1] == "1" %>
                                    <span class="perm_category category font" style="font-size: 13px;">パーマ</span>
                                <% end %>
                            </p>
                        </div>
                        <div class="menu_bottom">
                            <%= attachment_image_tag menu, :menu_image, fallback: "no_image.png", id: "prev_menu_img", style: "width: 110px; height: 110px;"%>
                            <p class="menu_explain"><%= menu.explanation %></p>
                        </div>
                    </div>
                    <% if menu.reservations.select {|reservation| reservation.start_time == @time && reservation.user_id != nil}.present? %>
                        <p class="exist_calendar_reservation">予約有り</p>
                    <% end %>
                <% end %>
            </div>
       `
$(".back_dark").html(html);
$(".back_dark").fadeIn();

app/views/hairdressers/reservations/new.html.erb
<div class="container center" style="padding-top: 50px;">
    <div class="time">
        <div class="error">
            <%= @error %>
        </div>
        <%= form_with(url: hairdressers_reservations_path, method: :post, local: true) do |f| %>
            <%= f.label :start_time %>                             
            <%= f.datetime_select :start_time, :start_year => @year.to_i, :start_hour => 06, :minute_step => 30, :use_month_numbers => true, :default => Date.new(@year.to_i, @month.to_i, @day.to_i)+@hour.to_i.hours+@min.to_i.minutes %>
            <%= f.hidden_field :menu_id, :value => @menu.id %>
            <%= f.submit '作成',class: "btn btn-primary make_btn"%>
        <%end%>
        <%= link_to "カレンダーに戻る", hairdressers_set_month_calendar_reservation_path(menu_id: @menu.id), class: "to_month_calendar color" %>
    </div>
    <div>
        <table class="table">
            <thead>
                <th class="center">時間</th><th class="center">メニュー名</th><th class="center">予約した人</th><th class="center"></th>
            </thead>
            <% @reservations.each do |reservation| %>
                <% if reservation.user_id != nil %>
                    <% @user = User.find(reservation.user_id) %> <!--モデルを関連づけてreservation.user.nameとしたかったが、モデルを関連づけるとreservationのデータをsaveするときにuser_idも必ずsaveしなくてはならず、nilで保存したかったので関連付けは行っていない-->
                <% end %>
                <tbody>
                    <tr>
                        <td><%= reservation.start_time.hour %>時<%= reservation.start_time.min %>分</td>
                        <td><%= @menu.name %></td>
                        <% if reservation.user_id != nil %>
                            <td><%= @user.name %></td>
                        <% else %>
                            <td>予約なし</td>
                        <% end %>
                        <% if reservation.user_id == nil %>
                            <td>
                                <%= link_to "削除", hairdressers_reservation_path(reservation.id), method: :delete, class: "btn btn-danger", data: { confirm: '本当に削除しますか?' }  %>
                            </td>
                        <% end %>
                    </tr>
                </tbody>
            <% end %>
        </table>
    </div>
</div>

app/views/hairdressers/reservations/set_week_calendar_reservation.html.erb
<div class="container">

    <h3 class="please_reservation res_center">予定表を編集してください<%= link_to "月間カレンダーへ", hairdressers_set_month_calendar_reservation_path(menu_id: @menu.id), class: "to_month_calendar color" %></h3>

    <!--menuカード-->
    <%= render "menus/menu2" %>

    <!--記号の説明-->
    <div class="explain_simbol">
        <span style="color: red;" class="simbol">◎</span>予約可能
        <span style="color: blue;" class="simbol">◎</span>予約あり
        <span class="glyphicon glyphicon-remove simbol" aria-hidden="true"></span>予約不可
    </div>

    <!--ここから週間カレンダー-->
    <table class="week_reservation_table">
        <thead class="table_header" id="table_head">
            <%= render "home/thead" %>
        </thead>
        <tbody id="table_body">
            <tr>
                <!--左の時刻表-->
                <th class="border_right table_time">
                    <table>
                        <tbody class="times">
                            <% @clock_arry.each do |clock| %>
                                <tr>
                                    <th class="width4"><%= clock %></th>
                                </tr>
                            <% end %>
                        </tbody>
                    </table>
                </th>
                
                <!--バツマル-->
                <% for i in 0..(@date_arry.length - 1) do %>
                    <th class="border_right table_maru_batu">
                        <!--このテーブルは縦一列-->
                        <table>
                            <tbody class="simbols">
                                <% @time_arry.each do |time| %>
                                    <% if @date_arry[i] == time.to_date %>
                                        <tr>
                                            <td href="<%=time%>" id="<%=time.year%><%=time.month%><%=time.day%><%=time.hour%><%=time.min%>" , class="border_bottom function width3 td_color">
                                                <% if Reservation.find_by(start_time: time, menu_id: @menu.id).present? %>
                                                    <% if Reservation.find_by(start_time: time, menu_id: @menu.id).user_id != nil %> <!--その時間に予約している会員がいるかどうか-->
                                                        <p style='color: blue;' class="simbol_exist_reservation">◎</p>
                                                    <% else %>
                                                        <p style='color: red;' class="simbol_round exist_reservation">◎</p>
                                                    <% end %>
                                                <% else %> <!--予約を作成していない時間のとき-->
                                                    <p class="glyphicon glyphicon-remove simbol_remove not_reservation" aria-hidden="true"></p>
                                                <% end %>
                                            </td>
                                        </tr>
                                    <% end %>
                                <% end %>
                            </tbody>
                        </table>
                    </th>
                <% end %>
                    
                <!--右の時刻表-->
                <th class="table_time">
                    <table>
                        <tbody class="times">
                            <% @clock_arry.each do |clock| %>
                                <tr>
                                    <th class="width4"><%= clock %></th>
                                </tr>
                            <% end %>
                        </tbody>
                    </table>
                </th>

            </tr>
        </tbody>
    </table>

    <div class="change_form">
        <%= form_with(url: hairdressers_create_destroy_reservation_path, method: :post, local: true, id: "hairdresser_reservation_form") do |f| %>
            <%= f.hidden_field :menu_id, value: @menu.id %>
            <%= f.hidden_field :standard_day, value: @standard_day %>
            <%= f.submit "変更を保存", class: "btn btn-success reservation_btn" %>
        <% end %>
    </div>

</div>