config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #homeコントローラ
  root "home#user_top"
  get "hairdresser_top" => "home#hairdresser_top", as: "hairdresser_top"
  get "about" => "home#about", as: "about"
  get "deadline" => "home#deadline", as: "deadline"
  
  #users::reservationsコントローラ users::hairdressersコントローラ  namespaceを使う時は使っていないものより上に書く 思い通りのrutingにならないerrorがでた
  namespace :users do
    get "set_week_calendar_reservation" => "reservations#set_week_calendar_reservation", as: "set_week_calendar_reservation"
    get "set_month_calendar_reservation" => "reservations#set_month_calendar_reservation", as: "set_month_calendar_reservation"
    resources :reservations, only: [:edit, :index]
    patch "various_update" => "reservations#various_update", as: "various_update"
    post "pay" => "reservations#pay", as: "card_resevation_pay"
    post "cancel" => "reservations#cancel", as: "reservation_cancel"
    get "complete" => "reservations#complete", as: "complete"
    resources :hairdressers, only: [:show, :index]
  end
  
  #usersコントローラ
  resources :users, only: [:edit, :create, :update]
  post "user/resend" => "users#resend", as: "user_resend"
  patch "user/password" => "users#password_update", as: "user_password_update"
  post "user/login" => "users#login", as: "user_login"
  post "user/logout" => "users#logout", as: "user_logout"
  get "user/activation" => "users#activation", as: "user_activation"
  get "user/sex_choice" => "users#sex_choice", as: "sex_choice"
  post "user/twitter_create" => "users#twitter_create", as: "twitter_create"
  post "user/guide" => "users#guide", as: "user_guide"
  post "user/password_reset" => "users#password_reset", as: "user_password_reset"
  get "user/password_update_as_forget" => "users#password_update_as_forget", as: "user_password_update_as_forget"
  patch "user/password_update_when_not_login" => "users#password_update_when_not_login", as: "user_password_update_when_not_login"

  #twitter認証のコールバック
  get '/auth/:provider/callback' => 'users#twitter' #url入力だとrootにいく
  get "/auth/failure", :to => 'users#twitter_failure' #この書き方にしないとhomesコントローラを探しにいく

  #hairdressers::reservationsコントローラ namespaceを使う時は使っていないものより上に書く 思い通りのrutingにならないerrorがでた
  namespace :hairdressers do
      get "set_week_calendar_reservation" => "reservations#set_week_calendar_reservation", as: "set_week_calendar_reservation"
      post "create_destroy_reservation" => "reservations#create_destroy_reservation", as: "create_destroy_reservation"
      get "set_month_calendar_reservation" => "reservations#set_month_calendar_reservation", as: "set_month_calendar_reservation"
      get "calendar_index" => "reservations#calendar_index", as: "calendar_index"
      post "calendar_show" => "reservations#calendar_show", as: "calendar_show"
      resources :reservations, only: [:new, :index, :create, :destroy]
      get "cancel_index" => "reservations#cancel_index", as: "cancel_index"
  end

  #hairdressersコントローラ
  resources :hairdressers, only: [:show, :edit, :index, :create, :update]
  post "hairdresser/resend" => "hairdressers#resend", as: "hairdresser_resend"
  patch "hairdresser/password" => "hairdressers#password_update", as: "hairdresser_password_update"
  post "hairdresser/login" => "hairdressers#login", as: "hairdresser_login"
  post "hairdresser/logout" => "hairdressers#logout", as: "hairdresser_logout"
  get "hairdresser/wait/:id" => "hairdressers#wait", as: "hairdresser_wait"
  get "hairdresser/activation" => "hairdressers#activation", as: "hairdresser_activation"
  post "hairdresser/guide" => "hairdressers#guide", as: "hairdresser_guide"
  post "hairdresser/password_reset" => "hairdressers#password_reset", as: "hairdresser_password_reset"
  get "hairdresser/password_update_as_forget" => "hairdressers#password_update_as_forget", as: "hairdresser_password_update_as_forget"
  patch "hairdresser/password_update_when_not_login" => "hairdressers#password_update_when_not_login", as: "hairdresser_password_update_when_not_login"

  #adminsコントローラー
  get "admins/user_index" => "admins#user_index", as: "admins_user_index"
  get "admins/hairdresser_index" => "admins#hairdresser_index", as: "admins_hairdresser_index"
  get "admins/user_chart" => "admins#user_chart", as: "admins_user_chart"
  get "admins/hairdresser_chart" => "admins#hairdresser_chart", as: "admins_hairdresser_chart"
  get "admins/sell_chart" => "admins#sell_chart", as: "admins_sell_chart"
  get "admins/login_form" => "admins#login_form", as: "admins_login_form"
  post "admins/login" => "admins#login", as: "admins_login"
  get "admins/hairdresser_judge_index" => "admins#hairdresser_judge_index", as: "admins_hairdresser_judge_index"
  patch "admins/permit/:id" => "admins#permit", as: "admins_permit"
  get "admins/reject/:id" => "admins#reject_form", as: "admins_reject_form"
  patch "admins/reject/:id" => "admins#reject", as: "admins_reject"
  post "admins/logout" => "admins#logout", as: "admins_logout"
  
  #menusコントローラ
  resources :menus, only: [:new, :index, :create, :edit, :update]
  post "menus/status_down" => "menus#status_down", as: "status_down"
  get "menus/preparation" => "menus#preparation", as: "preparation"
  post "menus/status_update" => "menus#status_update", as: "status_update"
  get "menus/choice" => "menus#choice", as: "menu_choice"
  
  #searchコントローラ
  get "search/search_index" => "search#search_index", as: "search_index"
  post "search/top_hairdresser" => "search#top_hairdresser", as: "top_hairdresser"
  post "search_data" => "search#search_data", as: "search_data"
  get "search_data" => "search#search_data"
  post "strong_search" => "search#strong_search", as: "strong_search"
  get "strong_search" => "search#strong_search"
  post "today_hairdresser_and_menu" => "search#today_hairdresser_and_menu", as: "today_hairdresser_and_menu"
  post "tomorrow_hairdresser_and_menu" => "search#tomorrow_hairdresser_and_menu", as: "tomorrow_hairdresser_and_menu"

  #style_imagesコントローラ
  resources :style_images, only: [:edit, :update]
  post "destroy/preparation" => "style_images#destroy_preparation", as: "destroy_preparation"

  #user_cardsコントラーラ
  resources :user_cards, only: [:create, :destroy]
  
  #hairdresser_commentsコントローラ
  resources :hairdresser_comments, only: [:edit, :update, :index]

  #chatsコントローラ
  get "user_chat" => "chats#user_chat", as: "user_chat"
  get "hairdresser_chat" => "chats#hairdresser_chat", as: "hairdresser_chat"
  post "message_create" => "chats#message_create", as: "message_create"
  post "receive_message" => "chats#receive_message", as: "receive_message"
  post "room" => "chats#room", as: "room"
  post "notification" => "chats#notification"
  post "chat_room_search" => "chats#chat_room_search", as: "chat_room_search"

  #favoritesコントローラ
  resources :favorites, only: [:index, :create, :destroy]

  #noticesコントローラ
  post "notice/message" => "notices#notice_message_modal", as: "notice_message_modal" 
  post "notice/reservation" => "notices#notice_reservation_modal", as: "notice_reservation_modal" 
  post "notice/cancel" => "notices#notice_cancel_modal", as: "notice_cancel_modal" 

  mount ActionCable.server => '/cable'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def user_top
        #人気美容師 口コミが3件以上あり、評価平均が4.5以上の美容師のデータを取得
        @hairdressers = Hairdresser.select {|hairdresser| hairdresser.hairdresser_comments.where.not(rate: 0.0).length >= 3 && hairdresser.reputation_point/hairdresser.hairdresser_comments.where.not(rate: 0.0).length >= 4.5}

        #評判の美容師 口コミが2件以上あり、評価平均が4以上の美容師のデータをメニューのカテゴリーごとに取得
        @hairdressers_for_reputation = Hairdresser.select {|hairdresser| hairdresser.hairdresser_comments.where.not(rate: 0.0).length >= 2 && hairdresser.reputation_point/hairdresser.hairdresser_comments.where.not(rate: 0.0).length >= 4}.sample(10)
        @menus = @hairdressers_for_reputation.map {|hairdresser| hairdresser.menus}
        @menus.flatten!

        @cut_menus = @menus.select {|menu| menu.category[0,1] == "1" && menu.status == true}
        @color_menus = @menus.select {|menu| menu.category[1,1] == "1" && menu.status == true}
        @curly_menus = @menus.select {|menu| menu.category[2,1] == "1" && menu.status == true}
        @parma_menus = @menus.select {|menu| menu.category[3,1] == "1" && menu.status == true}

        @hairdresser_cut_id_arry = @cut_menus.map {|menu| menu.hairdresser_id}.uniq
        @hairdresser_color_id_arry = @color_menus.map {|menu| menu.hairdresser_id}.uniq
        @hairdresser_curly_id_arry = @curly_menus.map {|menu| menu.hairdresser_id}.uniq
        @hairdresser_parma_id_arry = @parma_menus.map {|menu| menu.hairdresser_id}.uniq

        @hairdresser_new = Hairdresser.new

        #gon
        gon.body = "white" #jsで背景を変える
        gon.fix = "header" #jsでheaderを固定する

        #alertを出現させる
        if session[:double] == true
            gon.double = true
            session[:double] = nil
        end
    end

    def hairdresser_top
        #gon
        gon.body ="white"
        gon.fix = "header"
        gon.display_none = "none"
    end

    def about #aboutページ
        #FAQまでスクロールさせる
        if params[:faq]
            gon.faq = true
        end
    end

    def deadline #URLの有効期限が切れています のページ
    end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_error.html.erb
 <% target.errors.full_messages.each do |message| %>
    <p><%= message %></p>
<% end %>

app/views/home/_thead.html.erb
<tr>
    <!--前の週へのリンク-->
    <% if @thead_for_user %>
        <% if @standard_day != Date.today %>
            <th rowspan="2" class="border_right border_bottom2 width1">
                    <%= link_to "前の一週間", users_set_week_calendar_reservation_path(option: "last", day: @standard_day, menu_id: @menu.id), class: "last_week link_last_next color" %>
            </th>
        <% else %> <!--linkを無効-->
            <th rowspan="2" class="border_right border_bottom2 width1 add1">
                <%= link_to "前の一週間", users_set_week_calendar_reservation_path(option: "last", day: @standard_day, menu_id: @menu.id), style: "pointer-events: none; color: grey;" %>
            </th>
        <% end %>
    <% elsif @thead_for_hairdresser %>
        <% if @standard_day != Date.today %>
            <th rowspan="2" class="border_right border_bottom2 width1">
                <%= link_to "前の一週間", hairdressers_set_week_calendar_reservation_path(option: "last", day: @standard_day, menu_id: @menu.id), class: "last_week link_last_next color" %>
            </th>
        <% else %> <!--linkを無効-->
            <th rowspan="2" class="border_right border_bottom2 width1 add1">
                <%= link_to "前の一週間", hairdressers_set_week_calendar_reservation_path(option: "last", day: @standard_day, menu_id: @menu.id), style: "pointer-events: none; color: grey;" %>
            </th>
        <% end %>
    <% elsif @calendar_for_index %>
        <% if @standard_day != Date.today %>
            <th rowspan="2" class="border_right border_bottom2 width1">
                <%= link_to "前の一週間", hairdressers_calendar_index_path(option: "last", day: @standard_day), class: "last_week link_last_next color" %>
            </th>
        <% else %> <!--linkを無効-->
            <th rowspan="2" class="border_right border_bottom2 width1 add1">
                <%= link_to "前の一週間", hairdressers_calendar_index_path(option: "last", day: @standard_day), style: "pointer-events: none; color: grey;" %>
            </th>
        <% end %>
    <% end %>

    <!--年月-->
    <% if  @diff >= 13%> <!--月をまたぐかまたがないか-->
        <th colspan="14" class="border_righ border_botto width2 height2 "><%= @standard_day.year %>年<%= @standard_day.month %>月</th>
    <% else %>
        <% if @diff + 1 >= 4 %>
            <th width="43" height="45" colspan="<%= @diff + 1 %>" class="border_right border_botto height2 "><%= @standard_day.year %>年<%= @standard_day.month %>月</th>
        <% else %>
            <th width="43" height="45" colspan="<%= @diff + 1 %>" class="border_right border_botto height2 "></th>
        <% end %>
        <% if 13 - @diff >= 4 %>
            <th width="43" height="45" colspan="<%= 13 - @diff  %>" class="border_righ border_botto height2 "><%= @standard_day.next_month.year %>年<%= @standard_day.next_month.month %>月</th>
        <% else %>
            <th width="43" height="45" colspan="<%= 13 - @diff  %>" class="border_righ border_botto height2 "></th>
        <% end %>
    <% end %>

    <!--次の週へのリンク-->
    <% if @thead_for_user %>
        <th rowspan="2" class="attr87 width1 add1 border_bottom2 border_left">
            <%= link_to "次の一週間", users_set_week_calendar_reservation_path(option: "next", day: @standard_day, menu_id: @menu.id), class: "next_week link_last_next color" %>
        </th>
    <% elsif @thead_for_hairdresser %>
        <th rowspan="2" class="attr87 width1 add1 border_bottom2 border_left">
            <%= link_to "次の一週間", hairdressers_set_week_calendar_reservation_path(option: "next", day: @standard_day, menu_id: @menu.id), class: "next_week link_last_next color" %>
        </th>
    <% elsif @calendar_for_index %>
        <th rowspan="2" class="attr87 width1 add1 border_bottom2 border_left">
            <%= link_to "次の一週間", hairdressers_calendar_index_path(option: "next", day: @standard_day), class: "next_week link_last_next color" %>
        </th>
    <% end %>
</tr>

<tr class="date_top"><!--theadの真ん中の 日付 曜日-->
    <% for i in 0..13 do %>
        <% @day = @standard_day + i %>
        <% if HolidayJp.holiday?(@day).present? %> <!--休日かどうか-->
            <th class="border_left border_bottom2 border_top width3 holiday_back2">
                <div class="holiday2"><%= (@standard_day + i).day %></div>
                <div class="holiday2">(祝)</div>
            </th>
        <% elsif @day.wday == 6 %> <!--土曜日かどうか-->
            <th class="border_left border_bottom2 border_top width3 holiday_back1">
                <div class="holiday1"><%= (@standard_day + i).day %></div>
                <div class="holiday1">(<%= %w(日 月 火 水 木 金 土)[(@standard_day+i).wday] %>)</div>
            </th>
        <% elsif @day.wday == 0 %> <!--日曜日かどうか-->
            <th class="border_left border_bottom2 border_top width3 holiday_back2">
                <div class="holiday2"><%= (@standard_day + i).day %></div>
                <div class="holiday2">(<%= %w(日 月 火 水 木 金 土)[(@standard_day+i).wday] %>)</div>
            </th>
        <% else %> <!--平日-->
            <th class="border_left border_bottom2 border_top width3">
                <%= (@standard_day + i).day %>
                <div>
                    (<%= %w(日 月 火 水 木 金 土)[(@standard_day+i).wday] %>)
                </div>
            </th>
        <% end %>
    <% end %>
</tr>
      

app/views/home/deadline.html.erb
<div class="center">
    <p style="font-size: 30px; padding-top: 150px;">申し訳ありません。このURLの有効期限はきれています。</p>
</div>

app/views/home/top.html.erb
<div class="main">
<%= link_to "adminへ", admins_hairdresser_judge_index_path %>
        <header>
            <%= link_to root_path do %>
                <img src="<%= asset_path "cho.png" %>" alt="" class="log">
            <% end %>
            <div class="container">
                <div class="sign_in_block">
                    <h2 class="cursor login">ログイン</h2>
                    <div class="answer">
                        <p class="cursor user_open_modal btn-succes">会員ログイン</p>
                        <p class="cursor hairdresser_open_modal btn-succes">美容師ログイン</p>
                    </div>
                </div>
                <div class="sign_up_block">
                    <h2 class="cursor sign_up">新規会員登録</h2>
                    <div class="answer2">
                        <p><%= link_to "会員登録",  new_user_path, class: " btn-succes" %></p>
                        <p><%= link_to "美容師登録", new_hairdresser_path, class: " btn-succes" %></p>
                    </div>
                </div>
            </div>
        </header>
        <div class="container main_content">
            <h3>500円で美容院に行ける!!</h3>
            <h3>カットもカラーもすべて500円!!</h3>
            <h3>登録無料!!</h3>
            <h3>今なら500ポイントプレゼント!!(1回利用無料)</h3>
        </div>
</div>

<div id="user_login_modal">
        <div class="login_page">
            <div id="user_close_modal">
                <span class="glyphicon glyphicon-remove cursor" aria-hidden="true"></span>
            </div>
            <h2 class="aaa">会員ログイン</h2>
            <div>
                <%= form_with(url: user_login_path, method: :post) do |f| %>
                    <p>メールアドレス</p>
                    <%= f.text_field :email %>
                    <p>パスワード</p>
                    <%= f.password_field :password %>
                    <%= f.submit "ログイン" %>
                <% end %>
            </div>
        </div>
</div>

<div id="hairdresser_login_modal">
        <div class="login_page">
            <div id="hairdresser_close_modal">
                <span class="glyphicon glyphicon-remove cursor" aria-hidden="true"></span>
            </div>
            <h2 class="bbb">美容師ログイン</h2>
            <div>
                <%= form_with(url: hairdresser_login_path, method: :post) do |f| %>
                    <p>メールアドレス</p>
                     <%= f.text_field :email %>
                    <p>パスワード</p>
                    <%= f.password_field :password %>
                    <%= f.submit "ログイン" %>
                <% end %>
            </div>
        </div>
</div>

app/views/home/user_top.html.erb
<div id="user_main">
    <div class="stand_out">
        <p class="publicity">自分にあった美容師が必ずみつかる!!</p>
        <div class="search_form_square">
            <h3 class="condition">条件から美容師を探す</h3>
            <div class="center">
                <div class="find center">
                    <%= link_to search_index_path(turn: 1) do %>
                        <div class="find_tag"><img src="<%= asset_path "menu_icon.png" %>" class="find_icon"><p class="find_content">メニューから探す</p></div>
                    <% end %>
                    <%= link_to search_index_path(turn: 3) do %>
                        <div class="find_tag"><img src="<%= asset_path "map.png" %>" class="find_icon"><p class="find_content">エリアから探す</p></div>
                    <% end %>
                </div>
                <div class="find center">
                    <%= link_to search_index_path(turn: 2) do %>
                        <div class="find_tag"><img src="<%= asset_path "clock_icon.png" %>" class="find_icon"><p class="find_content">日付から探す</p></div>
                    <% end %>
                    <%= link_to search_index_path(turn: 4) do %>
                        <div class="find_tag"><img src="<%= asset_path "current.png" %>" class="find_icon"><p class="find_content">現在地から探す</p></div>
                    <% end %>
                </div>
                <div>
                    <%= form_with(url: search_data_path, method: :post, local: true, class: "welcome") do |f| %>
                        <%= f.text_field :search_keyword, placeholder: "美容師名、メニュー名など", class: "form-control search_top2" %>
                        <button type="submit" class="btn btn-primary search_icon_btn2"> 
                            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                        </button> 
                    <% end %>
                </div>
            </div>
        </div>
    </div>
    <div class="circles">
        <div class="circle_top">
            <p class="propaganda_user">簡単予約!!</p>
        </div>
        <div class="circle_top">
            <p class="propaganda_user">一回500円!!</p>
        </div>
        <div class="circle_top">
            <p class="propaganda_user">コスパ高!!</p>
        </div>
    </div>
</div>
<p class="center beta_version">今現在このサイトはβ版です。このサイトでの予約は架空の予約となります。</p>
<div class="botttom_search">
    <%= link_to today_hairdresser_and_menu_path, method: :post do %>
        <div class="today">
            <h2 class="res_today">今日予約する</h2>
        </div>
    <% end %>
    <%= link_to tomorrow_hairdresser_and_menu_path, method: :post do %>
        <div class="tomorrow">
            <h2 class="res_tomorrow">明日予約する</h2>
        </div>
    <% end %>
</div>

<div>
    <!-- 人気美容師スライダー bootstrapだけ jsなし -->
    <% if @hairdressers.present? %>
        <div id="top_hairdresser_slider" class="container center">
            <div class="carousel slide" data-ride="carousel" data-interval="6000">
                <h2 class="" style="margin-top: 100px; font-family: serif;">人気美容師</h2>
                <div class="carousel-inner " style="height: 500px;">
                    <% i = 1 %>
                    <% @hairdressers.each do |hairdresser| %>
                        <% if i == 1 %>
                            <div class="item active">
                                <div style="text-align: center;">
                                    <%= link_to users_hairdresser_path(hairdresser.id), remote: true do %>
                                        <%= attachment_image_tag hairdresser, :hairdresser_image, size: "250x250", fallback: "no_image.png", class: "img-circle" %>
                                    <% end %>
                                </div>
                                <h3><%= hairdresser.name %></h3>
                                <div style="margin-top: 20px;">
                                    <%= hairdresser.introduction %>
                                </div>
                            </div>
                        <% else %>
                            <div class="item">
                                <div style="text-align: center;">
                                    <%= link_to users_hairdresser_path(hairdresser.id), remote: true do %>
                                        <%= attachment_image_tag hairdresser, :hairdresser_image, size: "250x250", fallback: "no_image.png", class: "img-circle" %>
                                    <% end %>
                                </div>
                                <h3><%= hairdresser.name %></h3>
                                <div style="margin-top: 20px;">
                                    <%= hairdresser.introduction %>
                                </div>
                            </div>
                        <% end %>
                        <% i += 1 %>
                    <% end %>
                </div>
                <a class="left carousel-control" href=".carousel" data-slide="prev" style="height: 0px; width: 0px;">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                </a>
                <a class="right carousel-control" href=".carousel" data-slide="next" style="height: 0px; width: 0px;">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                </a>
            </div>
        </div>
    <% else %>
        <h2 class="center" style="margin-top: 100px;">人気美容師</h2>
        <p class="center">ただいま準備中です。</p>
    <% end %>
</div>

<div class="container res_container">
    <h2 class="center reptation_hairdresser">カットが評判の美容師</h1>
    <div class="top">
        <% if @hairdresser_cut_id_arry.present? %>
            <%= render "home/reputation", hairdresser_id_arry: @hairdresser_cut_id_arry, menus: @cut_menus %>
        <% else %>
            <p>ただいま準備中です。</p>
        <% end %>
    </div>
</div>

<div class="container res_container">
    <h2 class="center reptation_hairdresser">カラーが評判の美容師</h2>
    <div class="top">
        <% if @hairdresser_color_id_arry.present? %>
            <%= render "home/reputation", hairdresser_id_arry: @hairdresser_color_id_arry, menus: @color_menus %>
        <% else %>
            <p>ただいま準備中です。</p>
        <% end %>
    </div>
</div>

<div class="container res_container">
    <h2 class="center reptation_hairdresser">縮毛矯正が評判の美容師</h1>
    <div class="top">
        <% if @hairdresser_curly_id_arry.present? %>
            <%= render "home/reputation", hairdresser_id_arry: @hairdresser_curly_id_arry, menus: @curly_menus %>
        <% else %>
            <p>ただいま準備中です。</p>
        <% end %>
    </div>
</div>

<div class="container res_container" style="margin-bottom: 100px;">
    <h2 class="center reptation_hairdresser">パーマが評判の美容師</h1>
    <div class="top">
        <% if @hairdresser_parma_id_arry.present? %>
            <%= render "home/reputation", hairdresser_id_arry: @hairdresser_parma_id_arry, menus: @parma_menus %>
        <% else %>
            <p>ただいま準備中です。</p>
        <% end %>
    </div>
</div>

<!-- 美容師のshowモーダルを表示するための記述 -->
<div id="hairdresser_show" class=""></div>